 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/incidents", type: :request do
  
  # Incident. As you add validations to Incident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Incident.create! valid_attributes
      get incidents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      incident = Incident.create! valid_attributes
      get incident_url(incident)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_incident_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      incident = Incident.create! valid_attributes
      get edit_incident_url(incident)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Incident" do
        expect {
          post incidents_url, params: { incident: valid_attributes }
        }.to change(Incident, :count).by(1)
      end

      it "redirects to the created incident" do
        post incidents_url, params: { incident: valid_attributes }
        expect(response).to redirect_to(incident_url(Incident.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Incident" do
        expect {
          post incidents_url, params: { incident: invalid_attributes }
        }.to change(Incident, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post incidents_url, params: { incident: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested incident" do
        incident = Incident.create! valid_attributes
        patch incident_url(incident), params: { incident: new_attributes }
        incident.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the incident" do
        incident = Incident.create! valid_attributes
        patch incident_url(incident), params: { incident: new_attributes }
        incident.reload
        expect(response).to redirect_to(incident_url(incident))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        incident = Incident.create! valid_attributes
        patch incident_url(incident), params: { incident: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested incident" do
      incident = Incident.create! valid_attributes
      expect {
        delete incident_url(incident)
      }.to change(Incident, :count).by(-1)
    end

    it "redirects to the incidents list" do
      incident = Incident.create! valid_attributes
      delete incident_url(incident)
      expect(response).to redirect_to(incidents_url)
    end
  end
end
