 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/incident_outcomes", type: :request do
  
  # IncidentOutcome. As you add validations to IncidentOutcome, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IncidentOutcome.create! valid_attributes
      get incident_outcomes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      incident_outcome = IncidentOutcome.create! valid_attributes
      get incident_outcome_url(incident_outcome)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_incident_outcome_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      incident_outcome = IncidentOutcome.create! valid_attributes
      get edit_incident_outcome_url(incident_outcome)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IncidentOutcome" do
        expect {
          post incident_outcomes_url, params: { incident_outcome: valid_attributes }
        }.to change(IncidentOutcome, :count).by(1)
      end

      it "redirects to the created incident_outcome" do
        post incident_outcomes_url, params: { incident_outcome: valid_attributes }
        expect(response).to redirect_to(incident_outcome_url(IncidentOutcome.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IncidentOutcome" do
        expect {
          post incident_outcomes_url, params: { incident_outcome: invalid_attributes }
        }.to change(IncidentOutcome, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post incident_outcomes_url, params: { incident_outcome: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested incident_outcome" do
        incident_outcome = IncidentOutcome.create! valid_attributes
        patch incident_outcome_url(incident_outcome), params: { incident_outcome: new_attributes }
        incident_outcome.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the incident_outcome" do
        incident_outcome = IncidentOutcome.create! valid_attributes
        patch incident_outcome_url(incident_outcome), params: { incident_outcome: new_attributes }
        incident_outcome.reload
        expect(response).to redirect_to(incident_outcome_url(incident_outcome))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        incident_outcome = IncidentOutcome.create! valid_attributes
        patch incident_outcome_url(incident_outcome), params: { incident_outcome: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested incident_outcome" do
      incident_outcome = IncidentOutcome.create! valid_attributes
      expect {
        delete incident_outcome_url(incident_outcome)
      }.to change(IncidentOutcome, :count).by(-1)
    end

    it "redirects to the incident_outcomes list" do
      incident_outcome = IncidentOutcome.create! valid_attributes
      delete incident_outcome_url(incident_outcome)
      expect(response).to redirect_to(incident_outcomes_url)
    end
  end
end
