default: &default
  adapter: postgresql
  username: postgres
  password: root
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: arc_development

test:
  <<: *default
  database: arc_test

production:
  <<: *default
  database: arc_production
  username: arc_webapp
